---
- name: Install latest httpd version
  ansible.builtin.dnf:
    name: httpd
    state: latest
- name: Add the user 'cdpuser' as a member of 'cdpuser' and 'www' groups
  ansible.builtin.user:
    name: cdpuser
    comment: CDP User
    shell: /sbin/nologin
    groups: cdpuser,www
- name: Update template and copy to destination server
  ansible.builtin.template:
    src: templates/cdp.conf.j2
    dest: /etc/httpd/httpd.conf/cdp.conf
- name: Enable ipv4 forwarding via sysctl
  ansible.builtin.copy:
    src: templates/updatecdp.sh.j2
    dest: /usr/bin/updatecdp.sh
    owner: cdpuser
    group: cdpuser
    mode: '0744'
- name: Ensure a job runs every 15 minutes and updates CRLs
  ansible.builtin.cron:
    name: "Update CDP"
    minute: "*/15"
    user: cdpuser
    job: "/bin/bash /usr/bin/updatecdp.sh >/dev/null 2>&1"
- name: Enable and start httpd service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
