---
- name: Install latest httpd version
  ansible.builtin.dnf:
    name: httpd
    state: latest
- name: Add the user 'cdpuser' 
  ansible.builtin.user:
    name: cdpuser
    comment: CDP User
    shell: /sbin/nologin
    group: apache
- name: Create http directory
  ansible.builtin.file:
    path: /var/www/cdp
    state: directory
    mode: '0664'
    owner: cdpuser
    group: apache
- name: Create script directory
  ansible.builtin.file:
    path: /usr/local/bin/updatecdp
    state: directory
    mode: '700'
    owner: cdpuser
- name: Update http template
  ansible.builtin.template:
    src: templates/cdp.conf.j2
    dest: /etc/httpd/conf.d/cdp.conf
- name: Copy script to '/usr/local/bin/'
  ansible.builtin.copy:
    src: templates/updatecdp.sh
    dest: /usr/local/bin/updatecdp/updatecdp.sh
    owner: cdpuser
    mode: '0740'
- name: Update script config template
  ansible.builtin.template:
    src: templates/updatecdp.conf.j2
    dest: /usr/local/bin/updatecdp/updatecdp.conf
    owner: cdpuser
    mode: '0740'
- name: Create cronjob to run script
  ansible.builtin.cron:
    name: "Update CDP"
    minute: "*/15"
    user: cdpuser
    job: "/bin/bash /usr/local/bin/updatecdp/updatecdp.sh >/dev/null 2>&1"
- name: Enable and start httpd service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: true
